apiVersion: v1
name: sso-keycloak
version: 1.9.0
appVersion: 7.6.2-build.2
description: Open Source Identity and Access Management For Modern Applications and Services
dependencies:
  - name: patroni
    version: 1.5.1
    repository: https://bcgov.github.io/sso-helm-charts
    tags:
      - patroni-enabled
