replicaCount: 1

image:
  repository: ghcr.io/bcgov/sso
  tag: 7.5-9-rc.2
  pullPolicy: Always

project: sso-keycloak
nameOverride: sso-keycloak
fullnameOverride: sso-keycloak

networkPolicies:
  enabled: true

service:
  type: ClusterIP
  port: 8080

# see https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.0/html-single/red_hat_jboss_enterprise_application_platform_for_openshift/index#configuring_dns_ping
pingService:
  enabled: true
  port: 8888

postgres:
  host: sso-patroni
  database: ssokeycloak
  port: 5432
  credentials:
    secret: sso-patroni-appusers
    usernameKey: username-appuser1
    passwordKey: password-appuser1
    username: postgres
    password: postgres
  poolSize:
    min: 5
    max: 20

# see https://github.com/keycloak/keycloak-containers/blob/master/server/README.md#start-a-keycloak-instance-with-custom-command-line-options
additionalServerOptions: "-Dkeycloak.profile.feature.authorization=enabled -Djboss.persistent.log.dir=/var/log/eap"

# see https://github.com/keycloak/keycloak-containers/blob/master/server/README.md#setting-up-tlsssl
tls:
  enabled: false

persistentLog:
  enabled: true
  storageClassName: netapp-file-standard
  path: /var/log/eap

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 1250m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}

patroni:
  install: true
  replicaCount: 3
  # RH-SSO v7.5-9 is not tested with PostgreSQL 14
  image:
    repository: registry.opensource.zalan.do/acid/spilo-13
    tag: 2.1-p1

  postgresMajorVersion: 13

  project: sso-keycloak
  nameOverride: sso-patroni
  fullnameOverride: sso-patroni

  additionalCredentials:
    ssokeycloak: ""

  env:
    ALLOW_NOSSL: "true"

  persistentVolume:
    size: 10Gi

  podDisruptionBudget:
    enabled: true
